config/routes.rb
Rails.application.routes.draw do
  resources :relocations
  resources :statuses
  resources :rankactives
  get '/search_active', to: 'users#search_active', as: 'search_active'
  devise_for :users
  scope '/admin' do
    resources :users
    
  end
  resources :roles
  resources :users
  resources :ubications do
    collection do
      post :import
    end
  end
  root "actives#index"
  patch 'actives/:id', to: 'actives#update'
  patch 'actives/:id/status', to: 'actives#down', as:'actives_down_status'
  delete 'actives/:id', to: 'actives#destroy'
  resources :actives do
    
    collection do
      get 'not_active'
      post :import1
      post :import2
    end
  end
  
  post 'actives/options', as: 'actives_options'
  post 'actives/optionss', as: 'actives_optionss'

  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :invoices
  resources :groups
  resources :destinations do
    collection do
      post :import
    end
  end
  
  resources :centers do
    collection do
      post :import
    end
  end
  resources :zones do
  collection do
    post :import
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/active.rb
class Active < ApplicationRecord
  include PgSearch::Model
  before_save :uppercase_fields
  pg_search_scope :search_full_text, against: {
    name: 'D',
    user_id: 'C',
    barcode: 'B',
    plate: 'A',
  }

    validates :plate, uniqueness: { scope: :rankactive_id, notice: "Ya existe para este padre." }
    validates :destination_id, presence: { message: "El destino es requerido." }
    validates :ubication_id, presence: { message: "La ubicación es requerida." }
    validates :user_id, presence: { message: 'Se necesita asignar un responsable. '}
    validates :barcode, presence: { message: 'se necesita que digites o pistolees la placa.- '}
    validates :rankactive_id, presence: { message: 'Se necesita especificar si es un padre o un hijo.  '}
  private

  def uppercase_fields
    self.name.upcase!
    # ... y así sucesivamente para cada campo del formulario que quieres convertir a mayúsculas
  end

end

app/models/active_type.rb
class ActiveType < ApplicationRecord
    before_save :uppercase_fields
    validates :id, presence: true
    validates :description, presence: true
    
    private
    def uppercase_fields
    self.description.upcase!
    end
end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
  load_and_authorize_resource
  protect_from_forgery with: :null_session, only: [:create, :update, :destroy]
  before_action :authorize_admin, only: [:index, :create, :update, :destroy]
  def import1
    file = params[:file]
    return redirect_to actives_path, notice: 'Sólo se admite formato de separación de comas (.CSV)' unless file.content_type == 'text/csv'

    CsvImportActivesService.new.call(file)

    redirect_to actives_path, notice: 'ACTIVOS IMPORTADOS EXITOSAMENTE'
  end
  def import2
    file = params[:file]
    return redirect_to actives_path, notice: 'Sólo se admite formato de separación de comas (.CSV)' unless file.content_type == 'text/csv'

    CsvImportActivesService2.new.call(file)

    redirect_to actives_path, notice: 'ACTIVOS IMPORTADOS EXITOSAMENTE'
  end

  # GET /actives or /actives.json
  def index
    @actives = Active.where(status: true)
    if params[:query_text].present?
      @actives = @actives.search_full_text(params[:query_text])
    end
  end

  def index_not_active
    @actives = Active.where(status: false)
    if params[:query_text].present?
      @actives = @actives.search_full_text(params[:query_text])
    end
  end

  def authorize_admin
    redirect_to user_path(current_user), alert: "No tienes acceso a esta sección" unless current_user.admin?
  end

  # GET /actives/1 or /actives/1.json
  def show
  end

  # GET /actives/new
  def new
    @centers= Center.all
    @active=Active.new
  end
  def options
    @destinations = Destination.where(center_id: params[:center_id])
  end
  def optionss
    @ubications = Ubication.where(destination_id: params[:destination_id])
  end

  # GET /actives/1/edit
  def edit
    @centers= Center.all
  end

  # POST /actives or /actives.json
  def create
    @active = Active.new(active_params)
    @active.plate = @active.barcode
    @centers= Center.all
    respond_to do |format|
      if @active.save
        format.html { redirect_to actives_path, notice: "el activo fue creado" }
        format.json { render :show, status: :created, location: @active }
      else
        flash[:error] = "No se pudo crear el activo. Verifique los datos e intente nuevamente. Revisa que hayas seleccionado la ubicación y el destino"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @active.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /actives/1 or /actives/1.json
  def update
    @centers= Center.all
    @active.plate = @active.barcode
    if params[:status].present?
      down
    else
      respond_to do |format|
        if @active.update(active_params)
          format.html { redirect_to actives_path, notice: "el activo fue actualizado" }
          format.json { render :show, status: :ok, location: @active }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @active.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def down
    @active.toggle(:status)
    @active.user_id = 80000403900
    @active.save
    respond_to do |format|
      format.html { redirect_to actives_url, notice: "El estado del activo fue actualizado exitosamente." }
      format.json { head :no_content }
    end
  end

  # DELETE /actives/1 or /actives/1.json
  def destroy
    active = Active.find(params[:id])
    active.destroy
    redirect_to actives_path, notice: 'Tu activo se ha eliminado correctamente', status: :see_other
  end



  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def active_params
      params.require(:active).permit(:id, :barcode,:center_id, :serial, :name, :dad, :destination_id, :ubication_id, :plate , :user_id, :rankactive_id, :status, :active_type_id)
    end
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/views/actives/_active.html.erb
<div class="container">
          <table class="table  table-striped table-hover text-dark">
                  <tr class="">
                    <th>SERIAL</th>
                    <td><%= active.serial %></td>
                  </tr>
                  <tr>
                    <th>PLACA</th>
                    <td><%= active.plate %></td>
                  </tr>
                  <tr>
                    <th>PLACA DEL PADRE</th>
                    <% if active.rankactive_id == 8 %>
                      <% parent_active = Active.find_by(rankactive_id: 7) %>
                      <% if parent_active %>
                        <% active.dad = parent_active.plate %>
                        <td><%= link_to " ", parent_active, :class=>"fa-solid fa-magnifying-glass text-dark btn", title: "ver datos del padre" %></td>
                      <% else %>
                        ...
                      <% end %>
                    <% else %>
                      <td>No tiene padre</td>
                    <% end %>
                  </tr>
                  <tr>
                    <th>TIPO DE ACTIVO</th>
                    <td><% a=ActiveType.find(active.active_type_id) %>
                              <%= a.description %></td>
                  </tr>
                  <tr>
                    <th>NOMBRE DEL ACTIVO</th>
                    <td><%= active.name %></td>
                  </tr>
                  <tr>
                    <th>CÉDULA DEL RESPONSABLE</th>
                    <td><%= active.user_id %></td>
                  </tr>
                  <tr>
                    <th>NOMBRE DEL RESPONSABLE</th>
                    <td><% a=User.find(active.user_id) %>
                              <%= a.name %></td>
                  </tr>
                  <tr>
                    <th>ESTADO</th>
                    <td><%= active.status %></td>
                  </tr>
                  <tr>
                    <th>JERARQUIA</th>
                    <td><% a=Rankactive.find(active.rankactive_id) %>
                              <%= a.name %></td>
                  </tr>
                  <tr>
                    <th>DESTINOS</th>
                    <td><% a=Destination.find(active.destination_id) %>
                              <%= a.description %></td>
                  </tr>
                  <tr>
                    <th>UBICACIÓN</th>
                    <td><% a=Ubication.find(active.ubication_id) %>
                              <%= a.name %></td>
                  </tr>
          </table>
</div>

app/views/actives/_form.html.erb
<%= form_with model: @active, remote: true do |form| %>
<% if active.errors.any? %>
  <% flash[:error] = "Han ocurrido un total de: #{pluralize(active.errors.count, "error(es)")}, en la creación del activo:" %>
    <% active.errors.full_messages.each do |message| %>
      <% flash[:error] << message %>
    <% end %>
<% end %>
<div class="container">
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
<div class="form-control bg-card-personal">
    <div class="row row-cols-3">
      <div class="col">
              
                        
              <div class="mb-3">
                <div class="form-group">
                  <%= form.label "Código de barras del activo", :class=>"form-label ", style: "display: block" %>
                  <%= form.text_field :barcode, :class=>"form-control border border-info rounded-2 open-modal-button" %>
                  <%= render 'shared/modal' %>
                </div>
              </div>
              <div class="mb-3">
              <div class="form-group">
                <%= form.label "Nombre del activo", :class=>"form-label  ", style: "display: block" %>
                <%= form.text_field :name, :class=>"form-control border border-info rounded-2" %>
              </div>
              </div>
              <div class="mb-3">
              <div class="form-group">
                <%= form.label "Serial del activo", :class=>"form-label  ", style: "display: block" %>
                <%= form.text_field :serial, :class=>"form-control border border-info rounded-2" %>
              </div>
              </div> 
              <div class ="mb-3">
                <div class="form-group">
                  <label class="form-label">Tipo de activo </label>
                  <%= form.select :active_type_id, options_from_collection_for_select(ActiveType.all, :id, :description),{}, {class: "form-control border border-info rounded-2"} %>
                </div>
              </div>

        </div>
      </div>
      <div class="col">
        <div class="">
          <div class="form-group">
              <label class="form-label">Estado? </label>
              <%= form.select :status, [["Activo", true], ["Inactivo", false]], {}, {class: "form-control border border-info rounded-2"} %>
          </div>
        </div>
          
        <div class ="mb-3">
          <div class="form-group">  
             <label class="form-label">Es padre o hijo?: </label>
             <% @rankactives = Rankactive.all %>
            <%= form.select :rankactive_id, [['Selecciona si es padre o hijo', nil]] + @rankactives.collect {|rankactive| [rankactive.name, rankactive.id]},{}, {class: "form-control border border-info rounded-2", id: "rankactive_select"} %>
          </div>
        </div>
        <script>
          $(document).ready(function(){
            $("#rankactive_select").change(function(){
               if(($(this).find(':selected').text() == "HIJO")){
                  $("#dad_input").prop("disabled", false);
                }else{
                  $("#dad_input").prop("disabled", true);
                }
              });
          })
        </script>
        <div class ="mb-3">
            <div class="form-group">  
              <label class="form-label">Padre </label>
                <%= form.number_field :dad, :class=>"form-control border border-info rounded-2 open-modal-button3", id: "dad_input" %>
                  <%= render 'shared/modalpadre' %>
            </div>
        </div>

        <div class ="">
          <div class="form-group">
            <label class="form-label">Responsable</label>
            <%= form.select :user_id, options_from_collection_for_select(User.all, :id, :name),{}, {class: "form-control border border-info rounded-2"} %>
          </div>
        </div>
      </div>
      </div>
      
        <div class="col">

          
              <div class="mb-3">
                <div id="centers">
                    <%= form.label "Centros de costo:", :class=>"form-label  ", style: "display: block" %>
                    <%= form.select :center, [['Escoja el centro de costo', nil]] + @centers.collect {|center| [center.name, center.id]},{}, {class: "form-control border border-info rounded-2"} %>
                </div>
              </div>
              <div class="mb-3">  
                <%= form.label "Destinos", :class=>"form-label", style: "display: block" %>
                <div id="destinations">
                
                </div>
              </div>
          
              <script type="text/javascript">
              
                $(document).ready(function() {
                  $('#active_center.form-control').on('change', function() {
                    $.ajax({
                      url:  "<%= actives_options_path %>",
                      type: "POST",
                      data: { center_id: $(this).val() },
                      success: function(data){
                        $('#active_destination_id.form-control').on('change', function() {
                            $.ajax({
                              url:  "<%= actives_optionss_path %>",
                              type: "POST",
                              data: { destination_id: $(this).val() },
                            });
                      });
                      }
                    });
                  });
                });
              </script>

            <div class="mb-3">
              <label class="form-label ">Definir ubicacion:</label>
                <div id="ubications">
                </div>           
            </div>
        
      </div>
      </div>
    <i class= "separar d-flex bi">
      <span class="">
        <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise text-dark btn') do %>
        <% end %>
          
      </span>
        <%= link_to "", actives_path, :class=>"bi bi-skip-backward-btn-fill text-dark btn", :title=>'Retornar a las zonas' %>
    </i>
    </div>
  </div>

         </div>
 </div>
 </div>
 <% end %>
 </div>

app/views/actives/edit.html.erb
<% flash.each do |type, message| %>
  <div class="flash <%= type %> alert alert-danger">
    <%= message %>
  </div>

<% end %>



<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> EDICION DE ACTIVOS</h3>
            <p class="text-center">A continuación digita los datos del ACTIVO que deseas editar.</p>
                <div class="centrarcard"><%= render "form", active: @active %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

app/views/actives/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
           <% if can? :create, Active %>
            <%= link_to " Nueva activo", new_active_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          <% end %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
            <%= form_with url: actives_path, method: :get do |form| %>
              <%= form.text_field :query_text, placeholder: "Busca el activo", onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
              <button class="btn btn-secondary" type="button">Buscar</button>
            <% end %>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h3>ACTIVOS</h3>
        </div>
            <table class="table  table-striped table-hover">
                  <tr class="text-dark">
                    <th scope="col">PLACA DE ACTIVO</th>
                    <th scope="col">C. DE COSTO</th>
                    <th scope="col">NOMBRE</th>
                    <th scope="col">RESPONSABLE</th>
                    <th scope="col">ESTADO</th>
                    <th scope="col">ACCIONES</th>
                  </tr>
                  
                      <div id="actives">
                      <div class ="container">
                        <% @actives.each do |active| %>
                          <tr>
                            <td>
                              <%= active.plate %>
                            </td>
                            <td>
                              <% a=Destination.find(active.destination_id) %>
                              <% b=Center.find(a.center_id) %>
                              <%= b.name %>
                            </td>
                            <td>
                              <%= active.name %>
                            </td>
                            <td>
                              <% a=User.find(active.user_id) %>
                              <%= a.name %>
                            </td>
                            <td>
                              <%= active.status %>
                            
                              
                            </td>
                            <td>
                              <i class="separar">
                              
                                <%= link_to "", active, :class=>"bi bi-eye-fill text-dark btn" %>
                                <% if can? :destroy, Active %>
                                <%= button_to "", actives_down_status_path(active), method: :patch, :title=>"Dar de baja", class: "text-dark bi bi-arrow-down btn" %>
                                <% end %>
                                <% if can? :edit, Active %>
                                <%= link_to "", edit_active_path(active), :title=>"Editar", :class=>" bi bi-pencil-fill text-dark btn" %>
                                <% end %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
            </div>
      </div> 
                  
  </div>
</div>
</div>

app/views/actives/new.html.erb
<% flash.each do |type, message| %>
  <div class="flash <%= type %> alert alert-danger">
    <%= message %>
  </div>
  
<% end %>




<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title ">REGISTRAR NUEVO ACTIVO</h3>
            <p class="text-center">A continuación digita los datos del ACTIVO que deseas crear.</p>
                <div class="centrarcard"><%= render "form", active: @active %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

<div class =" mt-3 container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h5 class="card-title ">REGISTRO MASIVO DE ACTIVOS PADRES</h5>
            <p class="text-center">Escoja un archivo en formato .CSV para la creación masiva de ACTIVOS PADRES</p>
               
            </div>
          </div>
            <div class ="text-center text-dark">
              <%= form_with url: import1_actives_path, method: :post do |form| %>
                <div class ="input-group">
                  <%= form.file_field :file, class:"form-control border border-info", accept: ".csv" %>
                  <%= form.button "", class:" btn btn-outline-secondary border border-info fa-solid fa-file-import", title:"Importar" %>
                </div>
              <% end %>
              
       

        <div class="col text-dark mt-3">
            <h5 class="card-title ">REGISTRO MASIVO DE ACTIVOS HIJOS</h5>
            <p class="text-center">Escoja un archivo en formato .CSV para la creación masiva de ACTIVOS HIJOS</p>
               
            </div>
          </div>
            <div class ="text-center text-dark">
              <%= form_with url: import2_actives_path, method: :post do |form| %>
                <div class ="input-group">
                  <%= form.file_field :file, class:"form-control border border-info", accept: ".csv" %>
                  <%= form.button "", class:" btn btn-outline-secondary border border-info fa-solid fa-file-import", title:"Importar" %>
                </div>
              <% end %>
            </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>        

app/views/actives/not_active.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
           <% if can? :create, Active %>
            <%= link_to " Nueva activo", new_active_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          <% end %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
            <%= form_with url: actives_path, method: :get do |form| %>
              <%= form.text_field :query_text, placeholder: "Busca el activo", onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
              <button class="btn btn-secondary" type="button">Buscar</button>
            <% end %>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h3>De baja</h3>
        </div>
            <table class="table  table-striped table-hover">
                  <tr class="text-dark">
                    <th>PLACA DE ACTIVO</th>
                    <th>C. DE COSTO</th>
                    <th>NOMBRE</th>
                    <th>RESPONSABLE</th>
                    <th>ESTADO</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="actives">
                        <% @actives.each do |active| %>
                        <% if active.status == false %>
                          <tr>
                            <td>
                              <%= active.plate %>
                            </td>
                            <td>
                              <% a=Destination.find(active.destination_id) %>
                              <% b=Center.find(a.center_id) %>
                              <%= b.name %>
                            </td>
                            <td>
                              <%= active.name %>
                            </td>
                            <td>
                              <% a=User.find(active.user_id) %>
                              <%= a.name %>
                            </td>
                            <td>
                              <%= active.status %>
                            
                              
                            </td>
                            <td>
                              <i class="separar">

                                <%= link_to "", active, :class=>"bi bi-eye-fill text-dark btn" %>
                                <% if can? :edit, Active %>
                                <%= button_to "", active_path(active), method: :patch, :title=>"Dar de baja", class: "text-dark bi bi-arrow-down btn" %>

                                <%= button_to "", active, method: :delete, :class=>"bi bi-trash  text-dark btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                                <%= link_to "", edit_active_path(active), :title=>"Editar", :class=>" bi bi-pencil-fill text-dark btn" %>
                                <% end %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>

                        <% end %>
                      </div>
            </table> 
      </div>
  </div>
</div>
</div>

app/views/actives/options.js.erb
var html = "<%= j(collection_select(:active, :destination_id, Destination.where(center_id: params[:center_id]), :id, :description, {prompt: "Selecciona un destino"}, {class: "form-control"})) %>";
$('#destinations').html(html);

app/views/actives/optionss.js.erb
var html = "<%= j(collection_select(:active, :ubication_id, Ubication.where(destination_id: params[:destination_id]), :id, :name, {}, {class: "form-control"})) %>";
$('#ubications').html(html);

app/views/actives/show.html.erb
<p style="color: green"><%= notice %></p>


<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> DATOS DEL ACTIVO</h3>
            <p class="text-center"><%= render @active %></p>
              <i>
                <ul class="separar d-flex">
                  <li><%= button_to "", @active, method: :delete, :title=>"Eliminar", :class=>"bi bi-trash btn" %></li>
                  <li><%= link_to "", edit_active_path(@active), :title=>"Editar", :class=>" bi bi-pencil-fill btn" %></li>
                  <li><%= link_to "", actives_path, :title=>"Regresar a zonas", :class=>" bi bi-skip-backward-fill btn" %></li>
                </ul>
              </i>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>