config/routes.rb
Rails.application.routes.draw do
  resources :relocations
  resources :statuses
  resources :rankactives
  get '/search_active', to: 'users#search_active', as: 'search_active'
  devise_for :users
  scope '/admin' do
    resources :users
    
  end
  resources :roles
  resources :users
  resources :ubications do
    collection do
      post :import
    end
  end
  root "actives#index"
  patch 'actives/:id', to: 'actives#update'
  patch 'actives/:id/status', to: 'actives#down', as:'actives_down_status'
  delete 'actives/:id', to: 'actives#destroy'
  resources :actives do
    
    collection do
      get 'not_active'
      post :import1
      post :import2
    end
  end
  
  post 'actives/options', as: 'actives_options'
  post 'actives/optionss', as: 'actives_optionss'

  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :invoices
  resources :groups
  resources :destinations do
    collection do
      post :import
    end
  end
  
  resources :centers do
    collection do
      post :import
    end
  end
  resources :zones do
  collection do
    post :import
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
      can :import, :all
    elsif user.regular?
      can :read, :all
    end
  end
end

app/models/active.rb
class Active < ApplicationRecord
  include PgSearch::Model
  before_save :uppercase_fields
  pg_search_scope :search_full_text, against: {
    name: 'D',
    user_id: 'C',
    barcode: 'B',
    plate: 'A',
  }

    validates :plate, uniqueness: { scope: :rankactive_id, notice: "Ya existe para este padre." }
    validates :destination_id, presence: { message: "El destino es requerido." }
    validates :ubication_id, presence: { message: "La ubicación es requerida." }
    validates :user_id, presence: { message: 'Se necesita asignar un responsable. '}
    validates :barcode, presence: { message: 'se necesita que digites o pistolees la placa.- '}
    validates :rankactive_id, presence: { message: 'Se necesita especificar si es un padre o un hijo.  '}
  private

  def uppercase_fields
    self.name.upcase!
    # ... y así sucesivamente para cada campo del formulario que quieres convertir a mayúsculas
  end

end

app/models/active_type.rb
class ActiveType < ApplicationRecord
    before_save :uppercase_fields
    validates :id, presence: true
    validates :description, presence: true
    
    private
    def uppercase_fields
    self.description.upcase!
    end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        name: 'B'

    }
    belongs_to :zone
    validates :name, :zone_id, presence: true
    has_many :destination, dependent: :destroy
    
    private
    def uppercase_fields
        self.name.upcase!
    end
    
end

app/models/destination.rb
class Destination < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id:'A',
        description: 'B',

    }
    belongs_to :center
    validates :description, :center_id, presence: true
    has_many :actives, dependent: :destroy
    has_many :ubications, dependent: :destroy
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/rankactive.rb
class Rankactive < ApplicationRecord
    before_save :uppercase_fields
    has_many :actives

    private
    def uppercase_fields
        self.name.upcase!
    end
end

app/models/role.rb
class Role < ApplicationRecord
    before_save :uppercase_fields
    has_many :users, dependent: :restrict_with_exception
    
    private
    def uppercase_fields
        self.description.upcase!
    end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/ubication.rb
class Ubication < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    
    pg_search_scope :search_full_text, against: {
        description: 'B',
        id: 'A'
    }
    has_many :actives, dependent: :destroy
    validates :id, presence: true
    belongs_to :destination
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :uppercase_fields
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    name: 'A',
    email: 'B'
}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  has_many :actives, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Regular' if role.nil?
  end
  def admin?
    role.name == 'Admin'
  end
  def regular?
    role.name == 'Regular'
  end
  private
  def uppercase_fields
      self.name.upcase!
  end
  
end

app/models/zone.rb
class Zone < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        description: 'B',
    }
    has_many :centers, dependent: :destroy
    validates :description, :id, presence: true
    def uppercase_fields
        self.description.upcase!
    end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  load_and_authorize_resource

  def import
    file = params[:file]
    return redirect_to centers_path, notice: 'Solo se admite formato por separación de comas (.CSV)' unless file.content_type == 'text/csv'

    CsvImportCentersService.new.call(file)

    redirect_to centers_path, notice: 'CENTROS DE COSTO IMPORTADOS EXITOSAMENTE'
  end


  # GET /zones or /zones.json
  def index
    @centers = Center.all
    if params[:query_text].present?
      @centers = @centers.search_full_text(params[:query_text])
    end
  end

  # GET /zones/1 or /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @center = Center.new

    
  end

  # GET /zones/1/edit
  def edit
    @center=Center.find(params[:id])
  end

  # POST /zones or /zones.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to centers_path, notice: 'Tu centro de costo se ha creado correctamente', status: :see_other }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1 or /zones/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to centers_path, notice: 'Tu centro de costo se ha actualizado correctamente', status: :see_other }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1 or /zones/1.json
  def destroy
    center = Center.find(params[:id])
    center.destroy
    redirect_to centers_path, notice: 'Tu centro de costo se ha eliminado correctamente', status: :see_other
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def center_params
      params.require(:center).permit(:id, :name, :zone_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/centers/_center.html.erb
<div id="<%= dom_id center %>">
  <p>
    <strong>Name:</strong>
    <%= center.name %>
  </p>

</div>

app/views/centers/_form.html.erb
<%= form_with(model: center) do |form| %>
  <% if center.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(center.errors.count, "error(es)") %> prohibieron que el centro se guardara:</h2>
      
      <ul>
        <% center.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
<div class="container form-control bg-card-personal">
  <div class="col align-self-center">
    <%= form.label "Identificador del centro de costo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :id, class: "form-control border border-info rounded-2" %>
  <div class="mb-3">
    <%= form.label "Nombre del centro de costo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control border border-info rounded-2" %>
  </div>
  <div class="mb-3">
      <label class="control-label">Seleccione una Zona: </label>
      <div class= "input-group mb-3 justify-content-center">
        <%= form.select :zone_id, options_from_collection_for_select(Zone.all, :id, :description),{}, {class: "form-control"} %>
      </div>
  </div>

  <div>
    <i class= "separar d-flex bi">
      <span class="">
        <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise text-dark btn') do %>
        <% end %>
          
      </span>
        <%= link_to "", centers_path, :class=>"bi bi-skip-backward-btn-fill text-dark btn", :title=>'Retornar a las zonas' %>
    </i>
  </div>
<% end %>
</div>
</div>

app/views/centers/edit.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> EDICION DE CENTRO DE COSTO</h3>
            <p class="text-center">A continuación digita los datos del centro de costo que deseas editar.</p>
                <div class="centrarcard"><%= render "form", center: @center %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

app/views/centers/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
            <%= link_to " Nuevo centro de costo", new_center_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
            <%= form_with url: centers_path, method: :get do |form| %>
              <%= form.text_field :query_text, placeholder: "Busca el centro de costo", onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
              <button class="btn btn-secondary" type="button">Buscar</button>
            <% end %>
        </form>
      </div>
    </div>
  </nav>
           

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h3>CENTROS DE COSTO</h3>
        </div>
            <table class="table  table-striped table-hover">
                  <tr class="text-dark">
                    <th>CÓDIGO</th>
                    <th>NOMBRE</th>
                    <th>ID ZONA</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="centers">
                        <% @centers.order('zone_id asc').each do |center| %>
                          <tr>
                            <td>
                              <%= center.id %>
                            </td>
                            <td>
                              <%= center.name %>
                            </td>
                            <td>
                              <%= center.zone_id %>
                            </td>
                            <td>
                              <i class="separar">
                              <%= button_to "", center, method: :delete, :class=>"bi bi-trash  text-dark btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                              <%= link_to "", edit_center_path(center), :title=>"Editar", :class=>" bi bi-pencil-fill text-dark btn" %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
            
      </div>
  </div>
</div>

app/views/centers/new.html.erb
<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> REGISTRAR NUEVO CENTRO DE COSTO</h3>
            <p class="text-center">A continuación digita los datos del centro de costo que deseas crear.</p>
                <div class="centrarcard"><%= render "form", center: @center %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

<div class =" mt-3 container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h5 class="card-title ">REGISTRO MASIVO DE CENTROS DE COSTO</h5>
            <p class="text-center">Escoja un archivo en formato .CSV para la creación masiva de Centros de costo</p>
               
            </div>
          </div>
            <div class ="text-center text-dark">
              <%= form_with url: import_centers_path, method: :post do |form| %>
                <div class ="input-group">
                  <%= form.file_field :file, class:"form-control border border-info", accept: ".csv" %>
                  <%= form.button "", class:" btn btn-outline-secondary border border-info fa-solid fa-file-import", title:"Importar" %>
                </div>
              <% end %>
            </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>        

app/views/centers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @center %>

<div>
  <%= link_to "Edit this center", edit_center_path(@center) %> |
  <%= link_to "Back to centers", centers_path %>

  <%= button_to "Destroy this center", @center, method: :delete %>
</div>