config/routes.rb
Rails.application.routes.draw do
  resources :relocations
  resources :statuses
  resources :rankactives
  get '/search_active', to: 'users#search_active', as: 'search_active'
  devise_for :users
  scope '/admin' do
    resources :users
    
  end
  resources :roles
  resources :users
  resources :ubications do
    collection do
      post :import
    end
  end
  root "actives#index"
  patch 'actives/:id', to: 'actives#update'
  patch 'actives/:id/status', to: 'actives#down', as:'actives_down_status'
  delete 'actives/:id', to: 'actives#destroy'
  resources :actives do
    
    collection do
      get 'not_active'
      post :import1
      post :import2
    end
  end
  
  post 'actives/options', as: 'actives_options'
  post 'actives/optionss', as: 'actives_optionss'

  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :invoices
  resources :groups
  resources :destinations do
    collection do
      post :import
    end
  end
  
  resources :centers do
    collection do
      post :import
    end
  end
  resources :zones do
  collection do
    post :import
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
      can :import, :all
    elsif user.regular?
      can :read, :all
    end
  end
end

app/models/active.rb
class Active < ApplicationRecord
  include PgSearch::Model
  before_save :uppercase_fields
  pg_search_scope :search_full_text, against: {
    name: 'D',
    user_id: 'C',
    barcode: 'B',
    plate: 'A',
  }

    validates :plate, uniqueness: { scope: :rankactive_id, notice: "Ya existe para este padre." }
    validates :destination_id, presence: { message: "El destino es requerido." }
    validates :ubication_id, presence: { message: "La ubicación es requerida." }
    validates :user_id, presence: { message: 'Se necesita asignar un responsable. '}
    validates :barcode, presence: { message: 'se necesita que digites o pistolees la placa.- '}
    validates :rankactive_id, presence: { message: 'Se necesita especificar si es un padre o un hijo.  '}
  private

  def uppercase_fields
    self.name.upcase!
    # ... y así sucesivamente para cada campo del formulario que quieres convertir a mayúsculas
  end

end

app/models/active_type.rb
class ActiveType < ApplicationRecord
    before_save :uppercase_fields
    validates :id, presence: true
    validates :description, presence: true
    
    private
    def uppercase_fields
    self.description.upcase!
    end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        name: 'B'

    }
    belongs_to :zone
    validates :name, :zone_id, presence: true
    has_many :destination, dependent: :destroy
    
    private
    def uppercase_fields
        self.name.upcase!
    end
    
end

app/models/destination.rb
class Destination < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id:'A',
        description: 'B',

    }
    belongs_to :center
    validates :description, :center_id, presence: true
    has_many :actives, dependent: :destroy
    has_many :ubications, dependent: :destroy
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/rankactive.rb
class Rankactive < ApplicationRecord
    before_save :uppercase_fields
    has_many :actives

    private
    def uppercase_fields
        self.name.upcase!
    end
end

app/models/role.rb
class Role < ApplicationRecord
    before_save :uppercase_fields
    has_many :users, dependent: :restrict_with_exception
    
    private
    def uppercase_fields
        self.description.upcase!
    end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/ubication.rb
class Ubication < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    
    pg_search_scope :search_full_text, against: {
        description: 'B',
        id: 'A'
    }
    has_many :actives, dependent: :destroy
    validates :id, presence: true
    belongs_to :destination
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :uppercase_fields
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    name: 'A',
    email: 'B'
}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  has_many :actives, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Regular' if role.nil?
  end
  def admin?
    role.name == 'Admin'
  end
  def regular?
    role.name == 'Regular'
  end
  private
  def uppercase_fields
      self.name.upcase!
  end
  
end

app/models/zone.rb
class Zone < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        description: 'B',
    }
    has_many :centers, dependent: :destroy
    validates :description, :id, presence: true
    def uppercase_fields
        self.description.upcase!
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(resource_name.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: active) do |form| %>
  <% if active.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(active.errors.count, "error") %> prohibited this active from being saved:</h2>

      <ul>
        <% active.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
<div class="container form-control bg-card-personal">
    <div class="row">
  <div class="col align-self-center">
          <div class="mb-3">
            <%= form.label "Placa del activo", :class=>"form-label fw-bolder ", style: "display: block" %>
            <%= form.text_field :plate, :class=>"form-control border border-info rounded-2" %>
          </div>
          <div class="mb-3">
              <%= form.label "Código de barras del activo", :class=>"form-label fw-bolder ", style: "display: block" %>
              <%= form.text_field :barcode, :class=>"form-control border border-info rounded-2" %>
          </div>
        <div class="mb-3">
          <div class="form-group">
              <label class="control-label col-sm-6">Estado? </label><br>
              <%= form.select :status, [["Activo", true], ["Inactivo", false]], {} %>
          </div>
          <div class ="mb-3">
          <div class="form-group">
            <label class="control-label col-sm-6">Tipo de activo </label>
            <%= form.select :active_type_id, options_from_collection_for_select(ActiveType.all, :id, :description) %>
             <label class="control-label col-sm-6">Es padre o hijo?: </label><br>
            <%= form.select :rankactive_id, options_from_collection_for_select(Rankactive.all, :id, :name) %>
          </div>
          </div>
        </div>
        
        </div>
      
        <div class="col align-self-center">
          <div class="mb-3">
            <%= form.label "Nombre del activo", :class=>"form-label fw-bolder ", style: "display: block" %>
            <%= form.text_field :name, :class=>"form-control border border-info rounded-2" %>
          </div>
          <div class="mb-3">
            <%= form.label "Serial del activo", :class=>"form-label fw-bolder ", style: "display: block" %>
            <%= form.text_field :serial, :class=>"form-control border border-info rounded-2" %>
          </div>  
  
            
          
        <div class="mb-3">
         <div class="form-group">
            <label class="control-label col-sm-6">Selecciona el centro de costo: </label>
              <%= collection_select( :active, :ubication_id, Center.all, :id, :name, { prompt: true }) %>       
          </div>
          <div class="form-group">
          
            <label class="control-label col-sm-6">Seleccione un Destino: </label>
            <%= collection_select( :active, :destination_id, Destination.all, :id, :description, { prompt: true }) %>

          </div>
          <div class="form-group">
            <label class="control-label col-sm-6">Ubicación: </label>
            <%= collection_select( :active, :ubication_id, Ubication.all, :id, :name, { prompt: true }) %>
          </div>

        <div class="form-group">
            <label class="control-label col-sm-6">Responsable</label>
            <%= form.select :user_id, options_from_collection_for_select(User.all, :id, :name) %>
        </div>
      </div>
      </div>
    </div>
    <i class= "separar d-flex bi">
          <span class="">
            <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise text-dark btn') do %>
              <i class="icon-up-arrow icon-white"></i>
            <% end %>
            
        </span>
          <%= link_to "", actives_path, :class=>"bi bi-skip-backward-btn-fill text-dark btn", :title=>'Retornar a los activos' %>
        </i>
         </div>
 </div>
 </div>
 <% end %>

app/views/shared/_modal.html.erb
                    <div class="modal" id="myModal">
                      
                       <div class="modal-dialog modal-dialog-centered ">
                        <div class="modal-content bg-modal-personal">
                          <div class="modal-header">
                            <h1 class="modal-title text-white fs-5" id="exampleModalToggleLabel">Pistolea el código de barras</h1>
                          <button type="button" class="btn-close data-dismiss" aria-label="Close"></button>
                          <script>
                            
                          </script>
                          </div>
                          <div class="modal-body">
                            <form>
                                <input type="number" class="form-control border border-info rounded-2" id="barcode-input">
                                <div class="modal-footer">
                                  <button class= "btn" id="save-barcode">Registrar</button>
                                </div>
                            </form>
                          </div>

                        </div>
                    </div>
                      <script>
                          var selectedInput = document.querySelector('.open-modal-button');
                          document.querySelector('.open-modal-button').addEventListener('click', function() {
                            document.querySelector('#myModal').setAttribute("style", "display: block;");
                          });
                          document.querySelector('.btn-close').addEventListener('click', function() {
                              document.querySelector('#myModal').setAttribute("style", "display: none;");
                            });
                          document.querySelector('#save-barcode').addEventListener('click', function(e) {
                            e.preventDefault();
                            var barcode = document.querySelector('#barcode-input').value;
                            // aqui se puede guardar el barcode en algun lugar
                            selectedInput.value = barcode
                            document.querySelector('#myModal').setAttribute("style", "display: none;");
                          });


                      </script>

app/views/shared/_modalpadre.html.erb
<div class="modal" id="myModal3">
                      
                       <div class="modal-dialog modal-dialog-centered ">
                        <div class="modal-content bg-modal-personal">
                          <div class="modal-header">
                            <h1 class="modal-title text-white fs-5" id="exampleModalToggleLabel">Pistolea el código de barras del padre</h1>                          </div>
                          <div class="modal-body">
                            <form>
                                <input type="number" class="form-control border border-info rounded-2" id="dad-input">
                                <div class="modal-footer">
                                  <button class= "btn" id="save-dad">Registrar</button>
                                </div>
                            </form>
                          </div>

                        </div>
                    </div>
                      <script>
                          var selectedInput3 = document.querySelector('.open-modal-button3');
                          document.querySelector('.open-modal-button3').addEventListener('click', function() {
                            document.querySelector('#myModal3').setAttribute("style", "display: block;");
                          });
                          document.querySelector('.btn-close').addEventListener('click', function() {
                              document.querySelector('#myModal3').setAttribute("style", "display: none;");
                            });
                          document.querySelector('#save-dad').addEventListener('click', function(e) {
                            e.preventDefault();
                            var dad = document.querySelector('#dad-input').value;
                            // aqui se puede guardar el dad en algun lugar
                            selectedInput3.value = dad
                            document.querySelector('#myModal3').setAttribute("style", "display: none;");
                          });
                      </script>

app/views/shared/_modalplaca.html.erb
                     <div class="modal" id="myModal2">
                      
                       <div class="modal-dialog modal-dialog-centered ">
                        <div class="modal-content bg-modal-personal">
                          <div class="modal-header">
                            <h1 class="modal-title text-white fs-5" id="exampleModalToggleLabel">Pistolea el código de barras</h1>
                          <button type="button" class="btn-close data-dismiss" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <form>
                                <input type="number" class="form-control border border-info rounded-2" id="plate-input">
                                <div class="modal-footer">
                                  <button class= "btn" id="save-plate">Registrar</button>
                                </div>
                            </form>
                          </div>

                        </div>
                    </div>
                      <script>
                          var selectedInput2 = document.querySelector('.open-modal-button2');
                          document.querySelector('.open-modal-button2').addEventListener('click', function() {
                            document.querySelector('#myModal2').setAttribute("style", "display: block;");
                          });
                          document.querySelector('.btn-close').addEventListener('click', function() {
                              document.querySelector('#myModal2').setAttribute("style", "display: none;");
                            });
                          document.querySelector('#save-plate').addEventListener('click', function(e) {
                            e.preventDefault();
                            var plate = document.querySelector('#plate-input').value;
                            // aqui se puede guardar el plate en algun lugar
                            selectedInput2.value = plate
                            document.querySelector('#myModal2').setAttribute("style", "display: none;");
                          });
                      </script>

app/views/shared/_nav.html.erb
<nav class=" sep navbar navbar-expand-sm bg-rednav navbar">
      <div class="container-fluid">
        <a class="navbar-brand" href="">
          <%= image_tag("record.png", :class => "", :width => "80px") %>
        </a>   
          <h3><%=link_to 'APPOPERACIONES', root_path, class: 'navbar-brand text-white'%></h3>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
        
        <% if @current_user&.admin? and user_signed_in? %>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
            
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Maestros</a>
              
              <ul class="dropdown-menu">
                <li> 
                    <%= link_to "Ir a Zonas", zones_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                  <%= link_to "Ir a Centros de Costo", centers_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                    <%= link_to "Ir a Destinos", destinations_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                <%= link_to "Ir a Ubicaciones", ubications_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                   <%= link_to "Ir a De baja", not_active_actives_path, :class=>"dropdown-item text-dark" %>
                </li>
                   <%= link_to "Ir a Activos", actives_path, :class=>"dropdown-item text-dark" %>
                <li> 
                    <%= link_to "Ir a Tipos de Activo", active_types_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li> 
                    <%= link_to "Ir a jerarquias Activo", rankactives_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                    <%= link_to "Ir a Usuarios", users_path, :class=>"dropdown-item text-dark "  %>
                </li>
                <li>
                    <%= link_to "Ir a Roles", roles_path, :class=>"dropdown-item text-dark "  %>
                </li>
              </ul>
              
            </li>
          </ul>
          
        </div>
        <% elsif @current_user&.regular? and user_signed_in? %>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
              
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Opciones</a>
                
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Mis activos asociados", user_path(current_user), :class=>"dropdown-item text-dark " %>
                  </li>
                    <%= link_to "Ir a activos", actives_path, :class=>"dropdown-item text-dark" %>              
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        <% end %>


          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown">
              <% if user_signed_in? %>
                <%= current_user.name %>
              <% else %>
                Configuración
              <% end %>
              </a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <%= link_to "Perfil", user_path(current_user), :class=>"dropdown-item text-dark " %>
                  <%= button_to "Cerrar sesión", destroy_user_session_path, :class=>"dropdown-item text-dark ", method: :delete, data: { turbo:false } %>
                <% else %>
                  <%= link_to "Iniciar sesion", new_user_session_path, :class=>"dropdown-item text-dark" %>
                <% end %>

              </ul>
            </li>
          </ul>
      </div>
</nav>