config/routes.rb
Rails.application.routes.draw do
  resources :relocations
  resources :statuses
  resources :rankactives
  get '/search_active', to: 'users#search_active', as: 'search_active'
  devise_for :users
  scope '/admin' do
    resources :users
    
  end
  resources :roles
  resources :users
  resources :ubications do
    collection do
      post :import
    end
  end
  root "actives#index"
  patch 'actives/:id', to: 'actives#update'
  patch 'actives/:id/status', to: 'actives#down', as:'actives_down_status'
  delete 'actives/:id', to: 'actives#destroy'
  resources :actives do
    
    collection do
      get 'not_active'
      post :import1
      post :import2
    end
  end
  
  post 'actives/options', as: 'actives_options'
  post 'actives/optionss', as: 'actives_optionss'

  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :invoices
  resources :groups
  resources :destinations do
    collection do
      post :import
    end
  end
  
  resources :centers do
    collection do
      post :import
    end
  end
  resources :zones do
  collection do
    post :import
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
      can :import, :all
    elsif user.regular?
      can :read, :all
    end
  end
end

app/models/active.rb
class Active < ApplicationRecord
  include PgSearch::Model
  before_save :uppercase_fields
  pg_search_scope :search_full_text, against: {
    name: 'D',
    user_id: 'C',
    barcode: 'B',
    plate: 'A',
  }

    validates :plate, uniqueness: { scope: :rankactive_id, notice: "Ya existe para este padre." }
    validates :destination_id, presence: { message: "El destino es requerido." }
    validates :ubication_id, presence: { message: "La ubicación es requerida." }
    validates :user_id, presence: { message: 'Se necesita asignar un responsable. '}
    validates :barcode, presence: { message: 'se necesita que digites o pistolees la placa.- '}
    validates :rankactive_id, presence: { message: 'Se necesita especificar si es un padre o un hijo.  '}
  private

  def uppercase_fields
    self.name.upcase!
    # ... y así sucesivamente para cada campo del formulario que quieres convertir a mayúsculas
  end

end

app/models/active_type.rb
class ActiveType < ApplicationRecord
    before_save :uppercase_fields
    validates :id, presence: true
    validates :description, presence: true
    
    private
    def uppercase_fields
    self.description.upcase!
    end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        name: 'B'

    }
    belongs_to :zone
    validates :name, :zone_id, presence: true
    has_many :destination, dependent: :destroy
    
    private
    def uppercase_fields
        self.name.upcase!
    end
    
end

app/models/destination.rb
class Destination < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id:'A',
        description: 'B',

    }
    belongs_to :center
    validates :description, :center_id, presence: true
    has_many :actives, dependent: :destroy
    has_many :ubications, dependent: :destroy
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/rankactive.rb
class Rankactive < ApplicationRecord
    before_save :uppercase_fields
    has_many :actives

    private
    def uppercase_fields
        self.name.upcase!
    end
end

app/models/role.rb
class Role < ApplicationRecord
    before_save :uppercase_fields
    has_many :users, dependent: :restrict_with_exception
    
    private
    def uppercase_fields
        self.description.upcase!
    end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/ubication.rb
class Ubication < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    
    pg_search_scope :search_full_text, against: {
        description: 'B',
        id: 'A'
    }
    has_many :actives, dependent: :destroy
    validates :id, presence: true
    belongs_to :destination
    private
    def uppercase_fields
        self.description.upcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :uppercase_fields
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    name: 'A',
    email: 'B'
}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  has_many :actives, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Regular' if role.nil?
  end
  def admin?
    role.name == 'Admin'
  end
  def regular?
    role.name == 'Regular'
  end
  private
  def uppercase_fields
      self.name.upcase!
  end
  
end

app/models/zone.rb
class Zone < ApplicationRecord
    include PgSearch::Model
    before_save :uppercase_fields
    pg_search_scope :search_full_text, against: {
        id: 'A',
        description: 'B',
    }
    has_many :centers, dependent: :destroy
    validates :description, :id, presence: true
    def uppercase_fields
        self.description.upcase!
    end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  load_and_authorize_resource

  def import
    file = params[:file]
    return redirect_to zones_path, notice: 'Sólo se admite formato de separación de comas (.CSV)' unless file.content_type == 'text/csv'

    CsvImportZonesService.new.call(file)

    redirect_to zones_path, notice: 'ZONAS IMPORTADAS EXITOSAMENTE'
  end

  # GET /zones or /zones.json
  def index
    @zones = Zone.all
    if params[:query_text].present?
      @zones = @zones.search_full_text(params[:query_text])
    end
  end

  # GET /zones/1 or /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
    @zone=Zone.find(params[:id])
  end

  # POST /zones or /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to zones_path, notice: 'Tu zona se ha creado correctamente', status: :see_other }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1 or /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to zones_path, notice: 'Tu zona se ha actualizado correctamente', status: :see_other }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1 or /zones/1.json
  def destroy
    zone = Zone.find(params[:id])
    zone.destroy
    redirect_to zones_path, notice: 'Tu zona se ha eliminado correctamente', status: :see_other
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def zone_params
      params.require(:zone).permit(:id, :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_with(model: zone) do |form| %>
  
  <% if zone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibieron guardar la zona:</h2>

      <ul>
        <% zone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
 <div class="container  bg-card-personal w-75">
  <div class="col align-self-center">
    <%= form.label "Identificador de la zona", :class=>"form-label fw-bolder mt-2", style: "display: block" %>
    <%= form.text_field :id, class: "form-control border border-info rounded-2" %>
  </div>
  <div class="mb-3">
    <%= form.label "Nombre de la zona", :class=>"form-label fw-bolder mt-2", style: "display: block" %>
    <%= form.text_field :description, class: "form-control border border-info rounded-2" %>
  </div> 

  <div>
    <i class= "separar d-flex bi">
      <span class="">
        <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise text-dark btn') do %>
          <i class="icon-up-arrow icon-white"></i>
        <% end %>
          
      </span> 
        <%= link_to "", zones_path, :class=>"bi bi-skip-backward-btn-fill text-dark btn", :title=>'Retornar a las zonas' %>
    </i>
  </div>
<% end %>

app/views/zones/_zone.html.erb
<div class="container">
  <div id="<%= dom_id zone %>">
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
    <p>
    <strong>Identificador de la zona:</strong>
      <%= zone.id %>
    </p>
    <p>
      <strong>Nombre de la zona:</strong>
      <%= zone.description %>
    </p>
  </div>
</div>

app/views/zones/edit.html.erb
<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> EDICION DE ZONAS</h3>
            <p class="text-center">A continuación digita los datos de la zona que deseas editar.</p>
                <div class="centrarcard"><%= render "form", zone: @zone %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

app/views/zones/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->
  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
            <%= link_to " Nueva Zona", new_zone_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
            
            <%= form_with url: zones_path, method: :get do |form| %>
              <%= form.text_field :query_text, placeholder: "Busca la zona acá", onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
              <button class="btn btn-secondary" type="button">Buscar</button>
            <% end %>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h3>ZONAS</h3>
        </div>
            <table class="table  table-striped table-hover ">
                  <tr class="text-dark">
                    <th>CÓDIGO</th>
                    <th>NOMBRE</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="zones">
                        <% @zones.each do |zone| %>
                          <tr>
                            <td>
                              <%= zone.id%>
                            </td>
                            <td>
                              <%= zone.description %>
                            </td>
                            <td>
                              <i class="separar">
                              <%= button_to "", zone, method: :delete, :class=>"bi bi-trash  text-dark btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                              <%= link_to "", edit_zone_path(zone), :title=>"Editar", :class=>" bi bi-pencil-fill  text-dark btn" %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
      </div>
  </div>
</div>

app/views/zones/new.html.erb
<div class ="container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h3 class="card-title "> REGISTRAR NUEVA ZONA</h3>
            <p class="text-center">A continuación digita los datos de la zona que deseas crear.</p>
                <div class="centrarcard"><%= render "form", zone: @zone %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>

<div class =" mt-3 container tam-card-personal">
  <div class="row">
      <div class="col md-8">
  <div class="bg-card-personal card  text-white">
    <div class="card-body ">
      <h2 class="card-title"></h2>
      <div class="row">
        <%
=begin%>
 <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div> 
<%
=end%>
          <div class="col text-dark">
            <h5 class="card-title ">REGISTRO MASIVO DE ZONAS</h5>
            <p class="text-center">Escoja un archivo en formato .CSV para la creación masiva de Zonas</p>
               
            </div>
          </div>
            <div class ="text-center text-dark">
              <%= form_with url: import_zones_path, method: :post do |form| %>
                <div class ="input-group">
                  <%= form.file_field :file, class:"form-control border border-info", accept: ".csv" %>
                  <%= form.button "", class:" btn btn-outline-secondary border border-info fa-solid fa-file-import", title:"Importar" %>
                </div>
              <% end %>
            </div>
        </div>
      </div>  
    </div>
  </div>

      </div>
  </div>
</div>        

app/views/zones/show.html.erb
<p style="color: green"><%= notice %></p>

<div class ="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>INFORMACIÓN DE LA ZONA</h1>
        </div>
      </div>
  </div>
</div>

<div class ="container">
<div class="card card-dark text-white" style="width:100%">
  <div class="card-body">
    <h2 class="card-title"></h2>
    <div class="row">
      <div class=" logo col-auto"><%= image_tag("record.png", :class => "", :width => "400px") %></div>
        <div class="col">
          <h4 class="card-title ">DATOS DE LA ZONA</h4>
              <div class="centrarcard"><%= render @zone %></div>
              <i>
                <ul class="separar d-flex">
                  <li><%= button_to "", @zone, method: :delete, :title=>"Eliminar", :class=>"bi bi-trash btn" %></li>
                  <li><%= link_to "", edit_zone_path(@zone), :title=>"Editar", :class=>" bi bi-pencil-fill btn" %></li>
                  <li><%= link_to "", zones_path, :title=>"Regresar a zonas", :class=>" bi bi-skip-backward-fill btn" %></li>
                </ul>
              </i>
          </div>
        </div>
      </div>
    </div>  
  </div>
  
</div>
</div>